### ISSUE TITLE
bsicons not working with shinydashoard

### ISSUE THREAD

**Issue by sanjmeh** [rstudio/bsicons#3]
Hi,

I think `bsicons::bs_icon()` is not accepted in shinydashboard,

The following is extract of one of the menuItem, and the shiny app menu just stays with no icons.

```
  menuItem(text = "ETL Health Tracker",icon = icon(bsicons::bs_icon("lungs-fill",size = "1.5em")),
                           menuSubItem("API Tracker",tabName = "apitrack",icon = icon(bsicons::bs_icon("bug"))),
                           menuSubItem("DB tracker",tabName = "dbtrack",icon = icon(bsicons::bs_icon("box2-heart")))
                  )
```
![Screenshot 2023-03-10 at 2 27 06 AM](https://user-images.githubusercontent.com/3091624/224156389-64690c62-0426-4167-80f6-b32427fc50b8.png)

See output..

**Comment by cpsievert** [comment]
A fix for this would need to come from shinydashboard (it shouldn't be so overly strict about the icon type). 

Feel free to post an issue with shinydashboard, but just as a heads up, a fix for this probably won't happen since shinydashboard will soon be superceded by [`{bslib}`'s dashboarding tools](https://rstudio.github.io/bslib/articles/dashboards/index.html)
